### ISSUE TITLE
中文效果怎么样啊，也有这尝试发现你先做了

### ISSUE THREAD

**Issue by 425776024** [Mleader2/text_scalpel#1]

**Comment by Mleader2** [comment]
不好意思回复晚了，中文效果也很不错的。美中不足的是模型一般不会做出句式的修改，比如把一个被动句变成把字句。欢迎沟通！

**Comment by 425776024** [comment]
好的

**Comment by googlx** [comment]
> 不好意思回复晚了，中文效果也很不错的。美中不足的是模型一般不会做出句式的修改，比如把一个被动句变成把字句。欢迎沟通！

感谢您的贡献！请问一下能推荐一些可以进行句式子修改的模型吗，非常感谢！
