### ISSUE TITLE
仅仅在lcqmc数据集上测试，Exact score=7是什么原因呢

### ISSUE THREAD

**Issue by wuzhiye7** [Mleader2/text_scalpel#10]
嗨，按照你的指导步骤，仅仅使用了lcqmc数据构造训练测试集，最后得分 Exact score=7左右，与你额外添加的数据之后效果在29左右差异较大呢，请教下是什么原因呢  同时对比了swap为true/false的情况，评估差异不大

**Comment by Mleader2** [comment]
这个分数太低了，估计某个环节出了问题。具体是哪里有问题，我也判断不出来呀。但是你看其他人的评论都没说效果这么差，所以应该不是我代码的原因。你先自己检查一下吧，实在有问题咱们加微信沟通。

**Comment by wuzhiye7** [comment]
> 这个分数太低了，估计某个环节出了问题。具体是哪里有问题，我也判断不出来呀。但是你看其他人的评论都没说效果这么差，所以应该不是我代码的原因。你先自己检查一下吧，实在有问题咱们加微信沟通。

仅使用lcqmc数据 训练集为32000，验证集为8000 ，而默认sh脚本里数据为 NUM_TRAIN_EXAMPLES=310922，NUM_EVAL_EXAMPLES=5000  （好像不是0.8的比例），只是这里有差别，其他都与默认参数一致。 由于训练日志(python run_lasertagger.py)未显示loss变化值，所以不太好评估在lcqmc这3万2的数据30个epoch是否充分训练了  。最好有仅使用lcqmc数据的评估结论做参考对比，谢谢

**Comment by Mleader2** [comment]
这都是细节，影响不大。训练不充分也至于那么差吧。

**Comment by wuzhiye7** [comment]
> 这都是细节，影响不大。训练不充分也至于那么差吧。

我查看了下pred.tsv文件，效果感觉跟这位老哥反馈的差不多https://github.com/Mleader2/text_scalpel/issues/9#issuecomment-770540535

**Comment by Mleader2** [comment]
等我有时间只在lcqmc上做一下看看结果吧

**Comment by lizhzh8** [comment]
我也只使用一个lcqmc数据集，python score_main.py --prediction_file=./output/models/wikisplit_experiment_name/pred.tsv 后的结果是：
![11](https://user-images.githubusercontent.com/30767119/140270800-5f1f99f9-a9d3-4798-a079-a948c802ff90.png)

**Comment by lizhzh8** [comment]
> 我也只使用一个lcqmc数据集，python score_main.py --prediction_file=./output/models/wikisplit_experiment_name/pred.tsv 后的结果是： ![11](https://user-images.githubusercontent.com/30767119/140270800-5f1f99f9-a9d3-4798-a079-a948c802ff90.png)

另外说明下，预训练模型用的是Robert_tiny_clue。vocab.txt是8000多个的那个预训练模型
