### ISSUE TITLE
请问语料宝安机场用户QA是从哪里爬取的呢？

### ISSUE THREAD

**Issue by jimmy-walker** [Mleader2/text_scalpel#5]
感谢您的工作。请问宝安机场用户QA是从哪里爬取的呢？

**Comment by Mleader2** [comment]
那是具体业务的ＦＡＱ，别人整理好的。建议你结合自己的场景使用自己的语料，如果没有自己的语料只能用公开的数据集，例如ＬＣＱＭＣ。
